# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "interfax-ruby"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rafael Lima"]
  s.date = "2012-05-01"
  s.description = "Ruby wrapper based on savon for Interfax SOAP API"
  s.email = "contato@rafael.adm.br"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "interfax-ruby.gemspec",
    "lib/interfax.rb",
    "spec/fixtures/mickey01.jpg",
    "spec/fixtures/vcr_cassettes/cancel_file_upload.yml",
    "spec/fixtures/vcr_cassettes/cancel_file_upload_with_session.yml",
    "spec/fixtures/vcr_cassettes/sendfax_ex_2_authorized_default_values.yml",
    "spec/fixtures/vcr_cassettes/sendfax_ex_2_authorized_required_values.yml",
    "spec/fixtures/vcr_cassettes/start_file_upload_authorized.yml",
    "spec/fixtures/vcr_cassettes/start_file_upload_unauthorized.yml",
    "spec/fixtures/vcr_cassettes/upload_file_chunk_authorized.yml",
    "spec/interfax_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/savon.rb",
    "spec/support/vcr.rb"
  ]
  s.homepage = "http://github.com/rafaelp/interfax-ruby"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Ruby wrapper based on savon for Interfax SOAP API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<savon>, ["= 0.9.9"])
      s.add_development_dependency(%q<ruby-debug19>, ["= 0.11.6"])
      s.add_development_dependency(%q<rspec>, ["= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["= 3.12"])
      s.add_development_dependency(%q<bundler>, ["= 1.0.22"])
      s.add_development_dependency(%q<jeweler>, ["= 1.8.3"])
      s.add_development_dependency(%q<simplecov>, ["= 0.5.3"])
      s.add_development_dependency(%q<fakeweb>, ["= 1.3.0"])
      s.add_development_dependency(%q<vcr>, ["= 1.11.3"])
    else
      s.add_dependency(%q<savon>, ["= 0.9.9"])
      s.add_dependency(%q<ruby-debug19>, ["= 0.11.6"])
      s.add_dependency(%q<rspec>, ["= 2.8.0"])
      s.add_dependency(%q<rdoc>, ["= 3.12"])
      s.add_dependency(%q<bundler>, ["= 1.0.22"])
      s.add_dependency(%q<jeweler>, ["= 1.8.3"])
      s.add_dependency(%q<simplecov>, ["= 0.5.3"])
      s.add_dependency(%q<fakeweb>, ["= 1.3.0"])
      s.add_dependency(%q<vcr>, ["= 1.11.3"])
    end
  else
    s.add_dependency(%q<savon>, ["= 0.9.9"])
    s.add_dependency(%q<ruby-debug19>, ["= 0.11.6"])
    s.add_dependency(%q<rspec>, ["= 2.8.0"])
    s.add_dependency(%q<rdoc>, ["= 3.12"])
    s.add_dependency(%q<bundler>, ["= 1.0.22"])
    s.add_dependency(%q<jeweler>, ["= 1.8.3"])
    s.add_dependency(%q<simplecov>, ["= 0.5.3"])
    s.add_dependency(%q<fakeweb>, ["= 1.3.0"])
    s.add_dependency(%q<vcr>, ["= 1.11.3"])
  end
end

